Homework 15
nkokina/Salesforce_NatashaKokina_QA19 pull request #1
Opened 2022-07-29 17:33 UTC by nkokina

2022-07-31 08:36 UTC, voropa requested changes

2022-07-31 08:36 UTC, voropa commented on src/main/java/pages/BasePage.java
> +    private final static By SUFFIX = By.xpath("//*[@class='slds-input' and @name='suffix']");
Почему вы добавили эти локаторы в BasePage. вряд ли они есть на каждой наследуемой странице...

2022-07-31 08:36 UTC, voropa commented on src/main/java/tests/LeadsTests.java
> +enum Industry {
Please move this enum to separate class.
Create package enums

2022-07-31 08:36 UTC, voropa commented on src/main/java/tests/LeadsTests.java
> +        Assert.assertTrue(leadsPage.isSaveLeadsIconDisplayed(), "New Lead not save");
После сохранения, нужно  проверить, что данные сохранились корректно, для этого на LeadDetailsPage нужно выполнить ряд  проверок
![image](https://user-images.githubusercontent.com/14195681/182017807-a98e6db0-ed39-491e-a7bf-e960b9f5664f.png)

2022-07-31 15:03 UTC, nkokina commented on src/main/java/pages/BasePage.java
> +    private final static By SUFFIX = By.xpath("//*[@class='slds-input' and @name='suffix']");
они есть на страницах где мы создаем новые аккаунты, я их использовала два раза

2022-07-31 20:02 UTC, voropa commented on src/main/java/pages/BasePage.java
> +    private final static By SUFFIX = By.xpath("//*[@class='slds-input' and @name='suffix']");
Да, но они есть не на всех страницах, наследуемых от BasePage, поэтому, если хотите переиспользоваать какой-то код для страницы с аккаунтами и лидами, то создайте еще одну промежуточную абстрактную класс-страницу и унаследуйте от нее эти две

2022-08-07 21:24 UTC, voropa requested changes

2022-08-07 21:24 UTC, voropa commented on src/main/java/elements/LightningBaseCombobox.java
> +        if (Objects.nonNull(value)) {
Так если value == null то не  нужно никаких действий делать. а у вас все равно будет выполняться sendLeys и click(). А в этом if только scroll и sout(). Так что оберните всей действия внутри метода в этот if.
И пересмотрите всю логику этого метода. Там несколко лишних scollIntoView и system.out

2022-08-07 21:24 UTC, voropa commented on src/main/java/elements/LightningInput.java
> +        if (Objects.nonNull(value)) {
То же самое тут

2022-08-07 21:24 UTC, voropa commented on src/main/java/pages/modals/NewContactModal.java
> +    public void fillFord(Contact inputLead) {
Генри Форд?)

2022-08-07 21:24 UTC, voropa commented on src/main/java/tests/AccountsTests.java
> +    public void createAccountTest(String accountName, Type type, String webSite, String description, String parentAccount,
Ой-ей. Мы же специально использовали value object и builder pattern, чтобы избежать вот этих 20+ входных ргументов у методов и работать с тестовыми обьектами типа Lead. Так что в data-provider вам тоже нужно передавать целый обьект Lead
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/14195681/183311419-a36f47ab-f570-41b4-a38b-623747483a26.png">

2022-08-07 21:27 UTC, voropa requested changes

2022-08-07 21:27 UTC, voropa commented on src/main/java/elements/LightningCombobox.java
> +    private final static String COMBOBOX_LOCATOR = "//*[@class='slds-truncate' and text()='%s']";
Выглядит, как не уникальный локатор. Вам же нужно искать опцию внутри конкретного дропдауна, поэтому локатор должен выглядеть как-то так:
//label[text()='%s']/локатор_до_опции_по_имени_с_%s
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/14195681/183311560-1a217ec4-db51-4437-b4e1-5617e9cc3f44.png">

2022-08-14 20:02 UTC, voropa requested changes

2022-08-14 20:02 UTC, voropa commented on src/main/java/elements/LightningCombobox.java
> +    private final static String COMBOBOX_LOCATOR_ACCOUNT = "//*[@class='uiMenuItem uiRadioMenuItem']//a[text()='%s']";
Если у вас разные локаторы на разных страницах, то значит под каждый из них нужно делать свой класс- декоратор, иначе теряетс смысл такого подхода, когда у нас в одном классе будет 100500 локаторов на все случаи жизни для работы с любыми элементами на разных страницах

2022-08-14 20:02 UTC, voropa commented on src/main/java/elements/LightningFormattedElement.java
> +        log.debug("Setting input value = %s to input with locator = %s", String.format(visibleTextLocator, label));
Тут вроде не setting, а getting должно быть по смыслу

2022-08-14 20:02 UTC, voropa commented on src/main/java/elements/LightningInput.java
> +    private final static String BUTTON_LOCATOR_ACCOUNT =
То же самое тут с локаторами, разделите это на несколько классов-декораторов

2022-08-14 20:02 UTC, voropa commented on src/main/java/pages/ContactDetailsPage.java
> +        String lastName = new LightningFormattedElement(driver, "Name").getText();
У вас получается last name и first name берется одно  и то же значение со страницы и добаляется в модель Contact?

2022-08-19 09:31 UTC, voropa requested changes

2022-08-19 09:31 UTC, voropa commented on src/main/java/elements/account/LightningInputAccountName.java
> +            "//span[text()='%s']/../following-sibling::div/div/div/div/input";
Плохой локатор. Что если, в эту цепочку добавится еще один div, то он перестанет работать корректно.

2022-08-19 09:31 UTC, voropa commented on src/main/java/tests/ContactTests.java
> +//                {Contact.builder().lastName(faker.name().lastName()).firstName(faker.name().firstName()).salutation(Salutation.MS)
Почему закоментировано?

2022-08-20 20:00 UTC, nkokina commented on src/main/java/tests/ContactTests.java
> +//                {Contact.builder().lastName(faker.name().lastName()).firstName(faker.name().firstName()).salutation(Salutation.MS)
Забыла убрать)

2022-08-21 19:10 UTC, voropa approved these changes

2022-08-22 06:03 UTC, merged